### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by matthew-piziak** [ebpa/tui.el#2]
A picture is worth a thousand words, and screenshots are certainly the first thing I look for when I am looking at a UI package. If you like I can load up your demos and make a PR?

**Comment by ebpa** [comment]
Absolutely!  That would be wonderful.  Thank you!

If you have thoughts for demos I'd love to hear them too.

**Comment by matthew-piziak** [comment]
Sorry, I can't figure out how to install this library.
```
Error (use-package): tui/:catch: Cannot open load file: Not a directory, components/tui-button.el
```
This happens if I follow your installation instructions, but also with the following `straight.el` setup:
```
(use-package tui
  :straight (tui :type git :host github :repo "ebpa/tui.el"))
```

**Comment by ebpa** [comment]
@matthew-piziak Sorry about that!  I can't check right now, but try including a `:files` parameter with the folder names (I'm not using the use-package plugin):

    (use-package tui
      :straight (tui :type git :host github :repo "ebpa/tui.el" :files ("*.el" "components" "layout" "demo" "snippets")))

For my non-local configuration I use straight directly like so (this is for the dev branch):

    (straight-use-package
         '(tui :type git :host github :repo "ebpa/tui.el" :branch "dev" :files ("*.el" "components" "layout" "demo" "snippets")))

**Comment by matthew-piziak** [comment]
Thanks, that installation config worked.

The expander seems to work but Tic-Tac-Toe is wonky. 

![screenshot](https://user-images.githubusercontent.com/6801001/56435591-fe2d8500-62a6-11e9-8c52-7a9c401735b4.png)

**Comment by ebpa** [comment]
Great!  I should have mentioned that the tic-tac-toe rendering is broken at the moment.  It involves some indirect buffer rendering behavior (the `tui-absolute-container` component) that is currently buggy with recursive layouts.  I'm not sure when I'll have time to fix that since it was initially implemented to demonstrate the rather contrived tic-tac-toe example, but you will find that components are otherwise functional.

**Comment by ebpa** [comment]
@matthew-piziak FYI, I fixed the tic-tac-toe demo for Emacs Conf 2021 (`0.0.3`) and confirmed just now that it's functional in the latest version I just pushed (`0.0.4`).
