### ISSUE TITLE
`(require 'tui)` fails

### ISSUE THREAD

**Issue by ieure** [ebpa/tui.el#5]
Hi, I saw your EmacsConf talk on tui.el and thought I'd give it a whirl, as I'm trying to build more interactive tooling on Emacs.

Based on the README, I eval'd this code:

```emacs-lisp
(straight-use-package
 '(tui :type git :host github :repo "ebpa/tui.el" :files ("*.el" "components" "layout" "demo" "snippets")))

(require 'tui)
```

The `require` fails with an error:

```
Debugger entered--Lisp error: (void-variable tui-element-outline)
  byte-code("\302\10\301 \303\304\11!$\207" [tui-element-outline element tui-defun "Structure outline of ELEMENT and its children." tui-element-outline-string] 6)
  require(tui-dev)
  load-with-code-conversion("/home/ieure/.emacs.d/straight/build/tui/tui.el" "/home/ieure/.emacs.d/straight/build/tui/tui.el" nil t)
  require(tui)
  pp-eval-expression((require 'tui))
  pp-eval-last-sexp(nil)
  funcall-interactively(pp-eval-last-sexp nil)
  command-execute(pp-eval-last-sexp)
```

I assume this isn't expected behavior.  Is the README current?

**Comment by ebpa** [comment]
Hey!  Sorry I missed your comment.  When you tried this, there may very well have been a byte-compilation error.  I know there are currently some warnings with `0.0.4`/the latest few commits that I just pushed, but I think it should work for you.  If not, please let me know.
