### ISSUE TITLE
Did you mean to return t everytime for tui-render-element?

### ISSUE THREAD

**Issue by ag91** [ebpa/tui.el#6]
Hi!

I was starting playing around with your library and I noticed that in the latest release you always return `t` in `tui-render-element`: is that intended? It seemed useful to get the element reference :p

Thanks for this work!

**Comment by ebpa** [comment]
The original design of `tui-render-element` returned the element reference, but I'd changed it to return `t` to avoid the minibuffer noise printing the object reference when eval'ing tui expressions.  I've changed it back to return an element reference in `0.0.4` that I just pushed.

> Thanks for this work!

You're welcome!  Sorry for missing your comment!
